# Setup
title:               Marc Rußwurm
tagline:             'Research Associate at EPFL-ECEC'
description:         'Interested in Earth, Satellites, and the entire world. Contact me via marc.russwurm at epfl.ch'
url:                 https://marccoru.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Marc Rußwurm
  url:               https://twitter.com/marccoru
  email:             marc.russwurm@epfl.ch

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
